//! Short-lived, Host-bound authorization preflight for durable job receivers.

use chrono::{DateTime, SecondsFormat, Utc};
use serde::{Deserialize, Serialize};

use crate::job::{parse_strict_json, validate_project_address, validate_repository, JobRepository};
use crate::tenant::normalize_host;

/// Exact schema discriminator for job authorization requests and responses.
pub const JOB_AUTHORIZATION_SCHEMA_VERSION: &str = "buzz.job-authorization.v1";
/// Maximum validity of a server authorization response.
pub const JOB_AUTHORIZATION_TTL_SECONDS: i64 = 5;

/// Exact immutable bindings a receiver asks the relay to re-authorize.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JobAuthorizationRequest {
    /// Exact [`JOB_AUTHORIZATION_SCHEMA_VERSION`].
    pub schema_version: String,
    /// One-shot canonical UUID generated by the receiver.
    pub nonce: String,
    /// Stored signed kind-43001 event ID.
    pub request_event_id: String,
    /// Receiver-computed canonical request digest.
    pub semantic_digest: String,
    /// Server-resolved community UUID from `/api/context`.
    pub community_id: String,
    /// Canonical Host authority from `/api/context`.
    pub relay_host: String,
    /// Project home-channel UUID.
    pub channel_id: String,
    /// Exact kind-30621 project coordinate.
    pub project_address: String,
    /// Exact repository and checkout scope from the signed request.
    pub repository: JobRepository,
    /// Current request author.
    pub requester_pubkey: String,
    /// Current addressed worker and authenticated HTTP caller.
    pub recipient_pubkey: String,
}

/// Relay response to a successful immediate authorization preflight.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JobAuthorizationResponse {
    /// Exact [`JOB_AUTHORIZATION_SCHEMA_VERSION`].
    pub schema_version: String,
    /// Always true; denials are non-2xx responses.
    pub authorized: bool,
    /// Server-generated canonical UUID, consumed once by a durable receiver.
    pub authorization_id: String,
    /// Server issue time in canonical RFC3339 UTC form.
    pub issued_at: String,
    /// Expiry no more than five seconds after issue.
    pub expires_at: String,
    /// Exact echo of the validated request bindings.
    pub binding: JobAuthorizationBinding,
    /// Current Project head that supplied the home-channel binding.
    pub project_head_event_id: String,
    /// Exact repository coordinate listed by the current Project head.
    pub repository_coordinate: String,
    /// Current repository announcement referenced by that coordinate.
    /// This is linkage evidence, not a repository-authority grant.
    pub repository_announcement_event_id: String,
    /// Current authoritative owner of the requester, or the requester for a human.
    pub requester_owner_pubkey: String,
    /// Current authoritative owner of the addressed agent.
    pub recipient_owner_pubkey: String,
}

/// Request fields echoed verbatim by a successful authorization response.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JobAuthorizationBinding {
    /// Receiver nonce.
    pub nonce: String,
    /// Stored request event ID.
    pub request_event_id: String,
    /// Canonical semantic digest.
    pub semantic_digest: String,
    /// Server community UUID.
    pub community_id: String,
    /// Server Host authority.
    pub relay_host: String,
    /// Project channel UUID.
    pub channel_id: String,
    /// Project coordinate.
    pub project_address: String,
    /// Repository scope.
    pub repository: JobRepository,
    /// Requester pubkey.
    pub requester_pubkey: String,
    /// Recipient pubkey.
    pub recipient_pubkey: String,
}

impl From<&JobAuthorizationRequest> for JobAuthorizationBinding {
    fn from(request: &JobAuthorizationRequest) -> Self {
        Self {
            nonce: request.nonce.clone(),
            request_event_id: request.request_event_id.clone(),
            semantic_digest: request.semantic_digest.clone(),
            community_id: request.community_id.clone(),
            relay_host: request.relay_host.clone(),
            channel_id: request.channel_id.clone(),
            project_address: request.project_address.clone(),
            repository: request.repository.clone(),
            requester_pubkey: request.requester_pubkey.clone(),
            recipient_pubkey: request.recipient_pubkey.clone(),
        }
    }
}

impl JobAuthorizationRequest {
    /// Parse strict JSON, rejecting duplicate, unknown, and explicit-null fields.
    pub fn parse_strict(raw: &[u8]) -> Result<Self, String> {
        let text = std::str::from_utf8(raw)
            .map_err(|_| "job authorization request must be UTF-8 JSON".to_owned())?;
        let request: Self = parse_strict_json(text)?;
        request.validate()?;
        Ok(request)
    }

    /// Strictly validate syntax before any authority lookup.
    pub fn validate(&self) -> Result<(), String> {
        if self.schema_version != JOB_AUTHORIZATION_SCHEMA_VERSION {
            return Err("job authorization schema_version is unsupported".into());
        }
        validate_uuid("nonce", &self.nonce, false)?;
        validate_hex("request_event_id", &self.request_event_id, 64)?;
        validate_hex("semantic_digest", &self.semantic_digest, 64)?;
        validate_uuid("community_id", &self.community_id, false)?;
        validate_uuid("channel_id", &self.channel_id, false)?;
        if normalize_host(&self.relay_host) != self.relay_host || self.relay_host.is_empty() {
            return Err("relay_host must be canonical".into());
        }
        validate_project_address(&self.project_address).map_err(|error| error.to_string())?;
        validate_repository(&self.repository).map_err(|error| error.to_string())?;
        validate_pubkey("requester_pubkey", &self.requester_pubkey)?;
        validate_pubkey("recipient_pubkey", &self.recipient_pubkey)?;
        if self.requester_pubkey == self.recipient_pubkey {
            return Err("requester_pubkey and recipient_pubkey must differ".into());
        }
        Ok(())
    }
}

impl JobAuthorizationResponse {
    /// Validate server syntax, lifetime, and exact binding echo.
    pub fn validate_for(
        &self,
        request: &JobAuthorizationRequest,
        now: DateTime<Utc>,
    ) -> Result<(), String> {
        request.validate()?;
        if self.schema_version != JOB_AUTHORIZATION_SCHEMA_VERSION || !self.authorized {
            return Err("job authorization response is not an authorization".into());
        }
        validate_uuid("authorization_id", &self.authorization_id, false)?;
        if self.binding != JobAuthorizationBinding::from(request) {
            return Err("job authorization response bindings do not match the request".into());
        }
        validate_hex("project_head_event_id", &self.project_head_event_id, 64)?;
        validate_repository_coordinate(&self.repository_coordinate)?;
        validate_hex(
            "repository_announcement_event_id",
            &self.repository_announcement_event_id,
            64,
        )?;
        validate_pubkey("requester_owner_pubkey", &self.requester_owner_pubkey)?;
        validate_pubkey("recipient_owner_pubkey", &self.recipient_owner_pubkey)?;
        let issued = parse_canonical_time("issued_at", &self.issued_at)?;
        let expiry = parse_canonical_time("expires_at", &self.expires_at)?;
        if expiry <= issued
            || expiry.timestamp() - issued.timestamp() > JOB_AUTHORIZATION_TTL_SECONDS
        {
            return Err("job authorization response lifetime exceeds five seconds".into());
        }
        if now < issued - chrono::Duration::seconds(1) || now > expiry {
            return Err("job authorization response is stale or not yet valid".into());
        }
        Ok(())
    }
}

fn validate_uuid(name: &str, value: &str, allow_nil: bool) -> Result<(), String> {
    let parsed = uuid::Uuid::parse_str(value).map_err(|_| format!("{name} must be a UUID"))?;
    if (!allow_nil && parsed.is_nil()) || parsed.to_string() != value {
        return Err(format!("{name} must be a canonical non-nil UUID"));
    }
    Ok(())
}

fn validate_hex(name: &str, value: &str, length: usize) -> Result<(), String> {
    if value.len() != length
        || value != value.to_ascii_lowercase()
        || !value.bytes().all(|byte| byte.is_ascii_hexdigit())
    {
        return Err(format!("{name} must be canonical lowercase hex"));
    }
    Ok(())
}

fn validate_pubkey(name: &str, value: &str) -> Result<(), String> {
    let parsed = nostr::PublicKey::parse(value).map_err(|_| format!("{name} is not a pubkey"))?;
    if parsed.to_hex() != value {
        return Err(format!("{name} must be a canonical lowercase-hex pubkey"));
    }
    Ok(())
}

fn validate_repository_coordinate(value: &str) -> Result<(), String> {
    let mut parts = value.splitn(3, ':');
    if parts.next() != Some("30617") {
        return Err("repository_coordinate must use kind 30617".into());
    }
    let owner = parts
        .next()
        .ok_or_else(|| "repository_coordinate is missing its owner".to_owned())?;
    let d_tag = parts
        .next()
        .filter(|value| !value.is_empty())
        .ok_or_else(|| "repository_coordinate is missing its d tag".to_owned())?;
    validate_pubkey("repository_coordinate owner", owner)?;
    if d_tag.len() > 512 || d_tag.bytes().any(|byte| byte.is_ascii_control()) {
        return Err("repository_coordinate d tag is invalid".into());
    }
    Ok(())
}

fn parse_canonical_time(name: &str, value: &str) -> Result<DateTime<Utc>, String> {
    let parsed = DateTime::parse_from_rfc3339(value)
        .map_err(|_| format!("{name} must be RFC3339"))?
        .with_timezone(&Utc);
    if parsed.to_rfc3339_opts(SecondsFormat::Secs, true) != value {
        return Err(format!("{name} must use canonical UTC seconds"));
    }
    Ok(parsed)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn request() -> JobAuthorizationRequest {
        JobAuthorizationRequest {
            schema_version: JOB_AUTHORIZATION_SCHEMA_VERSION.into(),
            nonce: "12345678-1234-4234-8234-123456789abc".into(),
            request_event_id: "aa".repeat(32),
            semantic_digest: "bb".repeat(32),
            community_id: "22345678-1234-4234-8234-123456789abc".into(),
            relay_host: "relay.example".into(),
            channel_id: "32345678-1234-4234-8234-123456789abc".into(),
            project_address: format!("30621:{}:nemo", "11".repeat(32)),
            repository: JobRepository {
                canonical: "https://github.com/nemo-project/nemo".into(),
                github_issue: Some("1".into()),
                github_pr: None,
                github_run: None,
                base_sha: "cc".repeat(20),
                branch: "codex/a2a".into(),
                worktree_id: "a2a".into(),
                paths: vec!["crates/buzz-core".into()],
                contracts: vec!["contract:unit".into()],
            },
            requester_pubkey: nostr::Keys::generate().public_key().to_hex(),
            recipient_pubkey: nostr::Keys::generate().public_key().to_hex(),
        }
    }

    #[test]
    fn response_requires_exact_fresh_binding() {
        let request = request();
        let now = Utc::now();
        let response = JobAuthorizationResponse {
            schema_version: JOB_AUTHORIZATION_SCHEMA_VERSION.into(),
            authorized: true,
            authorization_id: uuid::Uuid::new_v4().to_string(),
            issued_at: now.to_rfc3339_opts(SecondsFormat::Secs, true),
            expires_at: (now + chrono::Duration::seconds(5))
                .to_rfc3339_opts(SecondsFormat::Secs, true),
            binding: JobAuthorizationBinding::from(&request),
            project_head_event_id: "dd".repeat(32),
            repository_coordinate: format!("30617:{}:nemo", "22".repeat(32)),
            repository_announcement_event_id: "ee".repeat(32),
            requester_owner_pubkey: request.requester_pubkey.clone(),
            recipient_owner_pubkey: nostr::Keys::generate().public_key().to_hex(),
        };
        assert!(response.validate_for(&request, now).is_ok());
        let mut wrong = response;
        wrong.binding.channel_id = uuid::Uuid::new_v4().to_string();
        assert!(wrong.validate_for(&request, now).is_err());
    }
}
